windows-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: windows-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
        BSNES_BRANCH: bus-v2
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    build_script:
        - pushd alttp-server && GOOS=windows GOARCH=amd64 go build && popd
        - apt-get update && apt-get install -y zip
        - zip alttp-server-${CIRRUS_CHANGE_IN_REPO:0:7}.zip alttp-server/alttp-server.exe
    binaries_artifacts:
        path: "alttp-*.zip"

windows-x86_32-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: windows-x86_32-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    build_script:
        - pushd alttp-server && GOOS=windows GOARCH=386 go build && popd
        - apt-get update && apt-get install -y zip
        - zip alttp-server-${CIRRUS_CHANGE_IN_REPO:0:7}.zip alttp-server/alttp-server.exe
    binaries_artifacts:
        path: "alttp-*.zip"

macOS-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: macOS-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    build_script:
        - pushd alttp-server && GOOS=darwin GOARCH=amd64 go build && popd
        - apt-get update && apt-get install -y zip
        - zip alttp-server-${CIRRUS_CHANGE_IN_REPO:0:7}.zip alttp-server/alttp-server
    binaries_artifacts:
        path: "alttp-*.zip"

linux-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: linux-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    build_script:
        - pushd alttp-server && GOOS=linux GOARCH=amd64 go build && popd
        - apt-get update && apt-get install -y zip
        - zip alttp-server-${CIRRUS_CHANGE_IN_REPO:0:7}.zip alttp-server/alttp-server
    binaries_artifacts:
        path: "alttp-*.zip"
