windows-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: windows-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    binaries_artifacts:
        path: "alttp-multiplayer-*.zip"

windows-x86_32-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: windows-x86_32-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    binaries_artifacts:
        path: "alttp-multiplayer-*.zip"

macOS-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: macOS-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    binaries_artifacts:
        path: "alttp-multiplayer-*.zip"

linux-x86_64-binaries_task:
    container:
        image: golang:1.13-buster

    environment:
        PACKAGER_TARGET_ARCH: linux-x86_64-binaries
        PACKAGER_WAIT_FOR_BUILD: 'true'
    package_script:
        - pushd packager && go build && popd && ./packager/alttp-packager
    binaries_artifacts:
        path: "alttp-multiplayer-*.zip"
